parameters:
#    kb_test.example.class: KieranBamforth\TestBundle\Example

services:
#    kb_test.example:
#        class: %kb_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
